config/routes.rb
Portfolio::Application.routes.draw do

  devise_for :users,
              controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :comments do
    resources :remarks
  end

  resources :projects do
    resources :remarks
  end

  root to: 'home#index'
  match 'about', to: 'about#index'

  match 'unmatched_route', to: "application#raise_not_found!"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :title, :published
  belongs_to :author, class_name: "User"
  has_many :remarks, as: :remarkable
  scope :published, where(published: true)

  def publish!
    published = true
    save!
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_filter :authenticate_user!, except: [:index, :show]
  # GET /comments
  # GET /comments.json
  def index
    @comments = policy_scope(Comment)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])
    @remarkable = @comment
    @remarks = @remarkable.remarks
    @remark = Remark.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])
    authorize @comment
    respond_to do |format|
      if @comment.save
        current_user.comments << @comment
        format.html do
        redirect_to @comment, notice: 'Post was successfully created.'
      end
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])
    authorize @comment
    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    authorize @comment
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/views/comments/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>
  <%= f.input :title %>
  <%= f.input :body %>
  <%= f.button :submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

</br>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
</br>
<h1 class="hgroup">Thought-Provoking Thoughts</h1>

<div class="col-lg-8">
<% @comments.each do |comment| %>
  <div id='<%= dom_id(comment) %>'>
    <h2 class="btitle"><%= comment.title %></h2>
    <p><%= comment.body %></p>
  </br>
    <td><%= link_to 'Read', comment, :class => 'icon-eye-open btn btn-success' %></td>
    <% if policy(comment).update? %>
    <td><%= link_to 'Edit', edit_comment_path(comment), :class => 'icon-edit btn btn-warning' %></td>
    <% end %>
    <% if comment.published? == false && policy(comment).publish? %>
      <td><%= link_to 'Publish', comment_path(comment, {comment: {published: true}}), :class => 'icon-print btn btn-default', method: :put, data: { confirm: 'Are you sure you want to publish?' }%></td>
    <% end %>
    <% if comment.published? == true && policy(comment).publish? %>
      <td><%= link_to 'Unpublish', comment_path(comment, {comment: {published: true}}), :class => 'icon-print btn btn-default', method: :put, data: { confirm: 'Are you sure you want to unpublish?' }%></td>
    <% end %>
    <% if policy(comment).destroy? %>
    <td><%= link_to 'Delete', comment, :class => 'icon-eraser btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </div>
<% end %>
<br />
<%= link_to 'New Post', new_comment_path, :class => 'btn btn-primary' %>
</div>

app/views/comments/new.html.erb
</br>
<h1>New Post</h1>

<%= render 'form' %>

app/views/comments/show.html.erb
</br>
<p>
  <b>Title:</b>
  <%= @comment.title %>
</p>

<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>

<p id="author">
  <b>By:</b>
  <%= @comment.author.email %>
</p>

<div class="move-up">
  <div class="well col-lg-6">
    <%= render 'remarks/form' %>
    <%= link_to 'Edit', edit_comment_path(@comment), :class => 'icon-edit btn btn-warning' %>
    <%= link_to 'Back', comments_path, :class => 'btn btn-success' %>
  </br>
  <%= render 'remarks/show' %>
</div>
</div>