config/routes.rb
Portfolio::Application.routes.draw do

  devise_for :users,
              controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :comments do
    resources :remarks
  end

  resources :projects do
    resources :remarks
  end

  root to: 'home#index'
  match 'about', to: 'about#index'

  match 'unmatched_route', to: "application#raise_not_found!"

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :technologies_used, :published, :image, :remote_image_url
  has_many :remarks, as: :remarkable
  belongs_to :author, class_name: "User"
  mount_uploader :image, ImageUploader

  validates :technologies_used, presence: true
  validates :name, length: { in: 4..255 }

  after_save :enqueue_image

  def image_name
    File.basename(image.path || image.filename) if image
  end

  def enqueue_image
    ImageWorker.perform_async(id, key) if key.present?
  end

  class ImageWorker
    include Sidekiq::Worker

    def perform(id, key)
      project = Project.find(id)
      project.key = key
      project.remote_image_url = project.image.direct_fog_url(with_path: true)
      project.save!
      project.update_column(:image_processed, true)
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @projects = Project.all
    @uploader = Project.new.image
    @uploader.success_action_redirect = new_project_url
  end

  def new
    @project = Project.new(key: params[:key])
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      current_user.projects << @project
      flash[:notice] = "Project was successfully added."
      redirect_to @project
    else
    flash[:alert] = "Project could not be saved"
    render :new
    end
  end

  def show
    @project = Project.find(params[:id])
    @remarkable = @project
    @remarks = policy_scope(@project.remarks)
    @remark = Remark.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project  = Project.find(params[:id])

    if @project.update_attributes(params[:project])
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
  end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to @project, notice: "Project was successfully deleted"
  end

end

app/views/projects/_form.html.erb
<%= form_for(@project, :html => {:multipart => true}) do |f| %>
<% if @project.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

  <ul>
    <% @project.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<%= f.hidden_field :key %>

<p>File: <%= @project.image_name %></p>

<div class="field col-lg-8">
  <%= f.label :name %><br />
  <%= f.text_field :name, :class => "form-control" %>
</div>
<div class="field col-lg-8">
  <%= f.label :technologies_used %><br />
  <%= f.text_field :technologies_used, :class => "form-control" %>
</br>
<div class="actions">
  <%= f.submit "Post", class: 'btn btn-primary' %>
</div>
</div>
<% end %>

app/views/projects/_project.html.erb
<div class="project" id="<%=dom_id(project) %>">
  <h3><%= project.name %></h3>
  <p><%= project.technologies_used %></p>
  <div class="nav">
    <%= link_to 'Show', project %> | <%= link_to 'Edit', edit_project_path(project) %> | <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?'} %>
  </div>
</div>

app/views/projects/_projects.html.erb
<div class="projects">
  <% if project.image_processed? %>
    <%= link_to image_tag(project.image_url(:thumb)), project if project.image? %>
  <% else %>
    <em>Processing...</em>
  <% end %>
  <div class="name"><%= project.name %></div>
  <div class="actions">
    <%= link_to "edit", edit_project_path(project) %> |
    <%= link_to "remove", project, :confirm => 'Are you sure?', :method => :delete %>
  </div>
</div>

app/views/projects/create.js.erb
$("#new_project").remove();
$("#new_link").show();
$('.project:last').append('<%= j render(@project) %>');

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render "form" %>

<%= link_to "Cancel", :back %>

app/views/projects/index.html.erb
</br>
<% @projects.each do |project| %>
<div class="project" id="<%= dom_id(project) %>">
  <h3><%= project.name %></h3>
  <p><%= project.technologies_used %></p>
  <%= image_tag project.image_url(:thumb).to_s %>
  <div class="nav">
    <%= link_to 'Show', project %> |
    <%= link_to 'Edit', edit_project_path(project) %> |
    <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</div>
<% end %>

<br />

<%= direct_upload_form_for @uploader do |f| %>
  <p><%= f.file_field :image %></p>
  <p><%= f.submit "Upload Image" %></p>
<% end %>

app/views/projects/new.html.erb
</br>
<h1>New project</h1>

<%= render "form" %>

app/views/projects/new.js.erb
$("#new_link").hide().after('<%= j render("form") %>')

app/views/projects/show.html.erb
</br>
<p>
  <b>Project:</b>
  <%= @project.name %>
</p>

<p>
  <b>Technologies used:</b>
  <%= @project.technologies_used %>
</p>

<p>
<%= image_tag @project.image_url(:thumb).to_s %>
</p>

<div class="move-up">
  <div class="well col-lg-6">
    <%= render 'remarks/form' %>
    <%= link_to 'Edit', edit_project_path(@project), :class => 'icon-edit btn btn-warning' %>
    <%= link_to 'Back', projects_path, :class => 'btn btn-success' %>
  </br>
  <%= render 'remarks/show' %>
</div>
</div>