config/routes.rb
Portfolio::Application.routes.draw do

  devise_for :users,
              controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :comments do
    resources :remarks
  end

  resources :projects do
    resources :remarks
  end

  root to: 'home#index'
  match 'about', to: 'about#index'

  match 'unmatched_route', to: "application#raise_not_found!"

end

app/views/layouts/_footer.html.erb
<% if user_signed_in? %>
<div class="navbar-fixed-bottom">
  <h6>
    <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
  </h6>
</div>

<% else %>

<div class="navbar-fixed-bottom">
  <h6 class="left">
    <%= link_to "Sign In", new_user_session_path %>
  </h6>
  <h6 class="right">
    <%= link_to "Sign Up", new_user_registration_path %>
  </h6>
</div>

<% end %>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'Thanh Huynh', root_path, :class => "navbar-brand"%>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li class="<%= 'active' if current_page?(about_path) %>">
              <%= link_to 'About', about_path %>
            </li>
            <li class="<%= 'active' if current_page?(projects_path) %>">
              <%= link_to "Portfolio", projects_path %>
            </li>
            <li>
              <a href="#">Resume</a>
            </li>
            <li class="<%= 'active' if current_page?(comments_path) %>">
              <%= link_to "Blog", comments_path %>
            </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li>
              <a href="https://github.com/thanhjamin" class="icon-github" target="_blank"></a>
            </li>
            <li>
              <a href="https://twitter.com/TDHuynh90" class="icon-twitter" target="_blank"></a>
            </li>
            <li>
              <a href="https://linkedin.com/in/huynhthanh" class="icon-linkedin" target="_blank"></a>
            </li>
          </ul>
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thanh's Portfolio</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- bootstrap flash -->
  <% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
    <%= value %>
    <% end %>
  </div>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>